#!/bin/bash

echo "🔍 Testing Database Connection for Reporting"
echo "============================================"

echo ""
echo "📊 Current Database Status:"
echo "Users: $(sqlite3 whistleblower.db 'SELECT COUNT(*) FROM users;')"
echo "Reports: $(sqlite3 whistleblower.db 'SELECT COUNT(*) FROM reports;')"
echo "Report reasons: $(sqlite3 whistleblower.db 'SELECT COUNT(*) FROM report_reasons;')"

echo ""
echo "🔍 Testing Student Search in Database:"
echo "======================================"
echo "Searching for 'pedro':"
sqlite3 whistleblower.db -header -column "SELECT login, display_name, email FROM users WHERE login LIKE '%pedro%' OR display_name LIKE '%pedro%' LIMIT 5;"

echo ""
echo "🔍 Testing Student Search in Database:"
echo "======================================"
echo "Searching for 'test':"
sqlite3 whistleblower.db -header -column "SELECT login, display_name, email FROM users WHERE login LIKE '%test%' OR display_name LIKE '%test%' LIMIT 5;"

echo ""
echo "💡 Issues with Reporting System:"
echo "================================"
echo "1. ✅ Database is connected and populated"
echo "2. ❌ Need proper OAuth login flow to work"
echo "3. ❌ Student search now uses local DB (should work better)"
echo ""
echo "🔧 To fix reporting:"
echo "=================="
echo "1. Login via /login endpoint first"
echo "2. This creates user in database"
echo "3. Then student search will work from local DB"
echo "4. Reporting will work because user exists in DB"
echo ""
echo "🚀 Quick test in browser:"
echo "========================"
echo "1. Start server: make dev"
echo "2. Go to: http://localhost:8080"
echo "3. Click 'Login with 42 Intra'"
echo "4. After login, try searching/reporting"